server:
  port: 8081

spring:
  aop:
    auto: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/zjserverdb?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username : root
    password : root

hsweb:
  app:
    name: zjserver
    version: 1.0.0

logging:
  level:
    org.hswebframework.web: DEBUG
    org.hswebframework.web.cache: WARN
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG

mybatis:
  mapper-locations: classpath:mappers/**/*.xml